name: 'Testing config dependencies and optional configuration'
type: module
package: Testing
# version: VERSION

# Information added by Drupal.org packaging script on 2024-04-03
version: '10.2.5'
project: 'drupal'
datestamp: 1712131088
